---
- hosts: "{{ test_hosts|default('all') }}"
  become: yes
  become_method: sudo
  tasks:
    - include: 'tasks/main.yml'
  vars_files:
    - 'defaults/main.yml'

  vars:
    #java_version: 8
    #java_subversion: 77
    java_install_jce: true
