#!/bin/sh
# simple script to delete messy .rpm files generated by Oracle(Sun) JDK;
# esp. sun-javadb series.
#


path_prefix=$1

messy_files=(
  'sun-javadb-*.rpm'
  '*-linux-amd64.rpm'
);


for item in "${messy_files[@]}"
do
  echo $item
  rm -f --interactive=never  $path_prefix/$item
done

exit 0
